from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


@dataclass(frozen=True)
class GCodeMove:
    x: float
    y: float
    z: float
    feed_rate: float | None = None
    command: str = "G1"


def write_gcode_file(file_path: str | Path, path_points: np.ndarray, feed_rate: int) -> None:
    file_path = Path(file_path)
    with file_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("; Delta robot path export\n")
        handle.write("; Generated by Delta_Gcode_Servo\n")
        handle.write("G21\n")
        handle.write("G90\n")
        handle.write(f"G1 F{feed_rate}\n")
        for point in path_points:
            handle.write(f"G1 X{point[0]:.3f} Y{point[1]:.3f} Z{point[2]:.3f}\n")
        handle.write("M2\n")


def parse_gcode_lines(lines: Iterable[str]) -> list[GCodeMove]:
    moves: list[GCodeMove] = []
    absolute_mode = True
    current_feed: float | None = None
    current_xyz = np.zeros(3, dtype=float)

    for raw_line in lines:
        line = raw_line.split(";", 1)[0].strip().upper()
        if not line:
            continue
        tokens = line.split()
        if not tokens:
            continue

        cmd = tokens[0]
        if cmd == "G21":
            continue
        if cmd == "G90":
            absolute_mode = True
            continue
        if cmd == "G91":
            absolute_mode = False
            continue
        if cmd == "M2":
            break
        if cmd not in {"G0", "G1"}:
            continue

        target = current_xyz.copy()
        seen_axis = False
        for token in tokens[1:]:
            axis = token[0]
            value = float(token[1:])
            if axis == "F":
                current_feed = value
                continue
            if axis not in {"X", "Y", "Z"}:
                continue
            idx = "XYZ".index(axis)
            seen_axis = True
            if absolute_mode:
                target[idx] = value
            else:
                target[idx] += value

        if seen_axis:
            current_xyz = target
            moves.append(
                GCodeMove(
                    x=float(current_xyz[0]),
                    y=float(current_xyz[1]),
                    z=float(current_xyz[2]),
                    feed_rate=current_feed,
                    command=cmd,
                )
            )

    return moves


def parse_gcode_file(file_path: str | Path) -> list[GCodeMove]:
    file_path = Path(file_path)
    with file_path.open("r", encoding="utf-8") as handle:
        return parse_gcode_lines(handle)
